const images = [
  {
    id: 1,
    src: "/images/models/bench/bench01.png",
    title: "bench01",
    type: "bench",
  },
  {
    id: 2,
    src: "/images/models/bench/bench02.png",
    title: "bench02",
    type: "bench",
  },
  {
    id: 3,
    src: "/images/models/bench/bench03.png",
    title: "bench03",
    type: "bench",
  },
  {
    id: 4,
    src: "/images/models/bench/bench04.png",
    title: "bench04",
    type: "bench",
  },
  {
    id: 5,
    src: "/images/models/bench/bench05.png",
    title: "bench05",
    type: "bench",
  },
  {
    id: 6,
    src: "/images/models/bench/bench06.png",
    title: "bench06",
    type: "bench",
  },
  {
    id: 7,
    src: "/images/models/bench/bench07.png",
    title: "bench07",
    type: "bench",
  },
  {
    id: 8,
    src: "/images/models/bench/bench08.png",
    title: "bench08",
    type: "bench",
  },
  {
    id: 9,
    src: "/images/models/bench/bench09.png",
    title: "bench09",
    type: "bench",
  },
  {
    id: 10,
    src: "/images/models/bench/bench10.png",
    title: "bench10",
    type: "bench",
  },
  {
    id: 11,
    src: "/images/models/bench/bench11.png",
    title: "bench11",
    type: "bench",
  },
  {
    id: 12,
    src: "/images/models/bench/bench12.png",
    title: "bench12",
    type: "bench",
  },
  {
    id: 13,
    src: "/images/models/crosses/cross01.png",
    title: "cross01",
    type: "crosses",
  },
  {
    id: 14,
    src: "/images/models/crosses/cross01D.png",
    title: "cross01D",
    type: "crosses",
  },
  {
    id: 15,
    src: "/images/models/crosses/cross02.png",
    title: "cross02",
    type: "crosses",
  },
  {
    id: 16,
    src: "/images/models/crosses/cross03.png",
    title: "cross03",
    type: "crosses",
  },
  {
    id: 17,
    src: "/images/models/crosses/cross03D.png",
    title: "cross03D",
    type: "crosses",
  },
  {
    id: 18,
    src: "/images/models/crosses/cross04.png",
    title: "cross04",
    type: "crosses",
  },
  {
    id: 19,
    src: "/images/models/crosses/cross05.png",
    title: "cross05",
    type: "crosses",
  },
  {
    id: 20,
    src: "/images/models/crosses/cross06.png",
    title: "cross06",
    type: "crosses",
  },
  {
    id: 21,
    src: "/images/models/crosses/cross07.png",
    title: "cross07",
    type: "crosses",
  },
  {
    id: 22,
    src: "/images/models/crosses/cross08.png",
    title: "cross08",
    type: "crosses",
  },
  {
    id: 23,
    src: "/images/models/crosses/cross09.png",
    title: "cross09",
    type: "crosses",
  },
  {
    id: 24,
    src: "/images/models/crosses/cross10.png",
    title: "cross10",
    type: "crosses",
  },
  {
    id: 25,
    src: "/images/models/crosses/cross11.png",
    title: "cross11",
    type: "crosses",
  },
  {
    id: 26,
    src: "/images/models/crosses/cross11D.png",
    title: "cross11D",
    type: "crosses",
  },
  {
    id: 27,
    src: "/images/models/crosses/cross12.png",
    title: "cross12",
    type: "crosses",
  },
  {
    id: 28,
    src: "/images/models/crosses/cross13.png",
    title: "cross13",
    type: "crosses",
  },
  {
    id: 29,
    src: "/images/models/crosses/cross14.png",
    title: "cross14",
    type: "crosses",
  },
  {
    id: 46,
    src: "/images/models/hearts/heart01.png",
    title: "heart01",
    type: "hearts",
  },
  {
    id: 47,
    src: "/images/models/hearts/heart02.png",
    title: "heart02",
    type: "hearts",
  },
  {
    id: 48,
    src: "/images/models/hearts/heart03.png",
    title: "heart03",
    type: "hearts",
  },
  {
    id: 49,
    src: "/images/models/hearts/heart04.png",
    title: "heart04",
    type: "hearts",
  },
  {
    id: 50,
    src: "/images/models/hearts/heart05.png",
    title: "heart05",
    type: "hearts",
  },
  {
    id: 51,
    src: "/images/models/hearts/heart06.png",
    title: "heart06",
    type: "hearts",
  },
  {
    id: 52,
    src: "/images/models/hearts/heart07.png",
    title: "heart07",
    type: "hearts",
  },
  {
    id: 53,
    src: "/images/models/hearts/heart08.png",
    title: "heart08",
    type: "hearts",
  },
  {
    id: 54,
    src: "/images/models/hearts/heart09.png",
    title: "heart09",
    type: "hearts",
  },
  {
    id: 55,
    src: "/images/models/hearts/heart10.png",
    title: "heart10",
    type: "hearts",
  },
  {
    id: 56,
    src: "/images/models/hearts/heart11.png",
    title: "heart11",
    type: "hearts",
  },
  {
    id: 57,
    src: "/images/models/hearts/heart12.png",
    title: "heart12",
    type: "hearts",
  },
  {
    id: 58,
    src: "/images/models/hearts/heart13.png",
    title: "heart13",
    type: "hearts",
  },
  {
    id: 59,
    src: "/images/models/hearts/heart14.png",
    title: "heart14",
    type: "hearts",
  },
  {
    id: 60,
    src: "/images/models/hearts/heart15.png",
    title: "heart15",
    type: "hearts",
  },
  {
    id: 61,
    src: "/images/models/hearts/heart16.png",
    title: "heart16",
    type: "hearts",
  },
  {
    id: 85,
    src: "/images/models/legacy/legacy01.png",
    title: "legacy01",
    type: "legacy",
  },
  {
    id: 86,
    src: "/images/models/legacy/legacy02.png",
    title: "legacy02",
    type: "legacy",
  },
  {
    id: 87,
    src: "/images/models/legacy/legacy03.png",
    title: "legacy03",
    type: "legacy",
  },
  {
    id: 88,
    src: "/images/models/legacy/legacy04.png",
    title: "legacy04",
    type: "legacy",
  },
  {
    id: 89,
    src: "/images/models/legacy/legacy04D.png",
    title: "legacy04D",
    type: "legacy",
  },
  {
    id: 90,
    src: "/images/models/legacy/legacy05.png",
    title: "legacy05",
    type: "legacy",
  },
  {
    id: 91,
    src: "/images/models/legacy/legacy06.png",
    title: "legacy06",
    type: "legacy",
  },
  {
    id: 92,
    src: "/images/models/legacy/legacy07.png",
    title: "legacy07",
    type: "legacy",
  },
  {
    id: 93,
    src: "/images/models/legacy/legacy08.png",
    title: "legacy08",
    type: "legacy",
  },
  {
    id: 94,
    src: "/images/models/legacy/legacy09.png",
    title: "legacy09",
    type: "legacy",
  },
  {
    id: 95,
    src: "/images/models/legacy/legacy10.png",
    title: "legacy10",
    type: "legacy",
  },
  {
    id: 96,
    src: "/images/models/legacy/legacy11.png",
    title: "legacy11",
    type: "legacy",
  },
  {
    id: 97,
    src: "/images/models/legacy/legacy12.png",
    title: "legacy12",
    type: "legacy",
  },
  {
    id: 98,
    src: "/images/models/legacy/legacy13.png",
    title: "legacy13",
    type: "legacy",
  },
  {
    id: 99,
    src: "/images/models/legacy/legacy14.png",
    title: "legacy14",
    type: "legacy",
  },
  {
    id: 100,
    src: "/images/models/legacy/legacy15.png",
    title: "legacy15",
    type: "legacy",
  },
  {
    id: 101,
    src: "/images/models/legacy/legacy16.png",
    title: "legacy16",
    type: "legacy",
  },
  {
    id: 102,
    src: "/images/models/legacy/legacy17.png",
    title: "legacy17",
    type: "legacy",
  },
  {
    id: 103,
    src: "/images/models/legacy/legacy18.png",
    title: "legacy18",
    type: "legacy",
  },
  {
    id: 104,
    src: "/images/models/legacy/legacy19.png",
    title: "legacy19",
    type: "legacy",
  },
  {
    id: 105,
    src: "/images/models/legacy/legacy20.png",
    title: "legacy20",
    type: "legacy",
  },
  {
    id: 106,
    src: "/images/models/legacy/legacy21.png",
    title: "legacy21",
    type: "legacy",
  },
  {
    id: 107,
    src: "/images/models/legacy/legacy22.png",
    title: "legacy22",
    type: "legacy",
  },
  {
    id: 108,
    src: "/images/models/legacy/legacy23.png",
    title: "legacy23",
    type: "legacy",
  },
  {
    id: 109,
    src: "/images/models/markers/ledge1.png",
    title: "ledger_30x60x4",
    type: "markers",
  },
  {
    id: 110,
    src: "/images/models/markers/Ledger_32x60x4.png",
    title: "ledger_32x60x4",
    type: "markers",
  },
  {
    id: 111,
    src: "/images/models/markers/Ledger_32x72x4.png",
    title: "ledger_32x72x4",
    type: "markers",
  },
  {
    id: 112,
    src: "/images/models/markers/Ledger_32x72x6.png",
    title: "ledger_32x72x6",
    type: "markers",
  },
  {
    id: 113,
    src: "/images/models/markers/Ledger_36x42x4.png",
    title: "ledger_36x42x4",
    type: "markers",
  },
  {
    id: 114,
    src: "/images/models/markers/Ledger_36x60x4.png",
    title: "ledger_36x60x4",
    type: "markers",
  },
  {
    id: 115,
    src: "/images/models/markers/Ledger_36x60x6.png",
    title: "ledger_36x60x6",
    type: "markers",
  },
  {
    id: 116,
    src: "/images/models/markers/Ledger_36x72x4.png",
    title: "ledger_36x72x4",
    type: "markers",
  },
  {
    id: 117,
    src: "/images/models/markers/Ledger_36x72x6.png",
    title: "ledger_36x72x6",
    type: "markers",
  },
  {
    id: 118,
    src: "/images/models/markers/Ledger_36x84x4.png",
    title: "ledger_36x84x4",
    type: "markers",
  },
  {
    id: 119,
    src: "/images/models/markers/Ledger_36x84x6.png",
    title: "ledger_36x84x6",
    type: "markers",
  },
  {
    id: 120,
    src: "/images/models/markers/Ledger_36x93x6.png",
    title: "ledger_36x93x6",
    type: "markers",
  },
  {
    id: 121,
    src: "/images/models/markers/Marker_20x19x4.png",
    title: "marker_20x19x4",
    type: "markers",
  },
  {
    id: 122,
    src: "/images/models/markers/Marker_20x28x4.png",
    title: "marker_20x28x4",
    type: "markers",
  },
  {
    id: 123,
    src: "/images/models/markers/Marker_24x12x4.png",
    title: "marker_24x12x4",
    type: "markers",
  },
  {
    id: 124,
    src: "/images/models/markers/Marker_24x14x4.png",
    title: "marker_24x14x4",
    type: "markers",
  },
  {
    id: 125,
    src: "/images/models/markers/Marker_26x28x4.png",
    title: "marker_26x28x4",
    type: "markers",
  },
  {
    id: 126,
    src: "/images/models/markers/Marker_26x28x6.png",
    title: "marker_26x28x6",
    type: "markers",
  },
  {
    id: 127,
    src: "/images/models/markers/Marker_28x16x4.png",
    title: "marker_28x16x4",
    type: "markers",
  },
  {
    id: 128,
    src: "/images/models/markers/Marker_30x32x4.png",
    title: "marker_30x32x4",
    type: "markers",
  },
  {
    id: 129,
    src: "/images/models/markers/Marker_30x36x4.png",
    title: "marker_30x36x4",
    type: "markers",
  },
  {
    id: 130,
    src: "/images/models/markers/Marker_36x36x4.png",
    title: "marker_36x36x4",
    type: "markers",
  },
  {
    id: 161,
    src: "/images/models/markers/Marker_48x12x4.png",
    title: "marker_48x12x4",
    type: "markers",
  },
  {
    id: 162,
    src: "/images/models/markers/Marker_48x14x4.png",
    title: "marker_48x14x4",
    type: "markers",
  },
  {
    id: 163,
    src: "/images/models/markers/Marker_48x16x4.png",
    title: "marker_48x16x4",
    type: "markers",
  },
  {
    id: 131,
    src: "/images/models/plural/plural01.png",
    title: "plural01",
    type: "plural",
  },
  {
    id: 132,
    src: "/images/models/plural/plural02.png",
    title: "plural02",
    type: "plural",
  },
  {
    id: 133,
    src: "/images/models/plural/plural03.png",
    title: "plural03",
    type: "plural",
  },
  {
    id: 134,
    src: "/images/models/plural/plural04.png",
    title: "plural04",
    type: "plural",
  },
  {
    id: 135,
    src: "/images/models/plural/plural05.png",
    title: "plural05",
    type: "plural",
  },
  {
    id: 136,
    src: "/images/models/plural/plural06.png",
    title: "plural06",
    type: "plural",
  },
  {
    id: 137,
    src: "/images/models/plural/plural07.png",
    title: "plural07",
    type: "plural",
  },
  {
    id: 138,
    src: "/images/models/plural/plural08.png",
    title: "plural08",
    type: "plural",
  },
  {
    id: 139,
    src: "/images/models/plural/plural09.png",
    title: "plural09",
    type: "plural",
  },
  {
    id: 140,
    src: "/images/models/plural/plural10.png",
    title: "plural10",
    type: "plural",
  },
  {
    id: 163,
    src: "/images/models/plural/plural11.png",
    title: "plural11",
    type: "plural",
  },
  {
    id: 141,
    src: "/images/models/slanted/slanted-24X16.png",
    title: "slanted-24X16",
    type: "slanted",
  },
  {
    id: 142,
    src: "/images/models/slanted/slanted-32X18.png",
    title: "slanted-32X18",
    type: "slanted",
  },
  {
    id: 143,
    src: "/images/models/slanted/slanted-48X24.png",
    title: "slanted-48X24",
    type: "slanted",
  },
  {
    id: 147,
    src: "/images/models/standard/standard_18x18.png",
    title: "standard_18x18",
    type: "standard",
  },
  {
    id: 148,
    src: "/images/models/standard/standard_24x24.png",
    title: "standard_24x24",
    type: "standard",
  },
  {
    id: 149,
    src: "/images/models/standard/standard_24x30.png",
    title: "standard_24x30",
    type: "standard",
  },
  {
    id: 150,
    src: "/images/models/standard/standard_42x24.png",
    title: "standard_42x24",
    type: "standard",
  },
  {
    id: 151,
    src: "/images/models/standard/standard_48x24.png",
    title: "standard_48x24",
    type: "standard",
  },
  {
    id: 152,
    src: "/images/models/standard/standard_60x30.png",
    title: "standard_60x30",
    type: "standard",
  },
  {
    id: 153,
    src: "/images/models/standard/standard_72x32.png",
    title: "standard_72x32",
    type: "standard",
  },
  {
    id: 190,
    src: "/images/models/statue/statue01.png",
    title: "statue01",
    type: "statue",
  },
  {
    id: 191,
    src: "/images/models/statue/statue02.png",
    title: "statue02",
    type: "statue",
  },
  {
    id: 192,
    src: "/images/models/statue/statue03.png",
    title: "statue03",
    type: "statue",
  },
  {
    id: 193,
    src: "/images/models/statue/statue04.png",
    title: "statue04",
    type: "statue",
  },
  {
    id: 194,
    src: "/images/models/statue/statue05.png",
    title: "statue05",
    type: "statue",
  },
  {
    id: 195,
    src: "/images/models/statue/statue06.png",
    title: "statue06",
    type: "statue",
  },
  {
    id: 196,
    src: "/images/models/statue/statue07.png",
    title: "statue07",
    type: "statue",
  },
  {
    id: 197,
    src: "/images/models/statue/statue08.png",
    title: "statue08",
    type: "statue",
  },
  {
    id: 198,
    src: "/images/models/statue/statue09.png",
    title: "statue09",
    type: "statue",
  },
  {
    id: 199,
    src: "/images/models/statue/statue10.png",
    title: "statue10",
    type: "statue",
  },
  {
    id: 200,
    src: "/images/models/statue/statue11.png",
    title: "statue11",
    type: "statue",
  },
  {
    id: 201,
    src: "/images/models/statue/statue12.png",
    title: "statue12",
    type: "statue",
  },
  {
    id: 202,
    src: "/images/models/statue/statue13.png",
    title: "statue13",
    type: "statue",
  },
  {
    id: 203,
    src: "/images/models/statue/statue14.png",
    title: "statue14",
    type: "statue",
  },
  {
    id: 204,
    src: "/images/models/statue/statue15.png",
    title: "statue15",
    type: "statue",
  },
  {
    id: 205,
    src: "/images/models/statue/statue16.png",
    title: "statue16",
    type: "statue",
  },
  {
    id: 206,
    src: "/images/models/statue/statue17.png",
    title: "statue17",
    type: "statue",
  },
  {
    id: 207,
    src: "/images/models/statue/statue18.png",
    title: "statue18",
    type: "statue",
  },
  {
    id: 208,
    src: "/images/models/statue/statue19.png",
    title: "statue19",
    type: "statue",
  },
  {
    id: 209,
    src: "/images/models/statue/statue19D.png",
    title: "statue19D",
    type: "statue",
  },
  {
    id: 210,
    src: "/images/models/statue/statue20.png",
    title: "statue20",
    type: "statue",
  },
  {
    id: 211,
    src: "/images/models/statue/statue21.png",
    title: "statue21",
    type: "statue",
  },
  {
    id: 212,
    src: "/images/models/statue/statue21D.png",
    title: "statue21D",
    type: "statue",
  },
  {
    id: 213,
    src: "/images/models/statue/statue22.png",
    title: "statue22",
    type: "statue",
  },
  {
    id: 214,
    src: "/images/models/statue/statue23.png",
    title: "statue23",
    type: "statue",
  },
  {
    id: 215,
    src: "/images/models/statue/statue24.png",
    title: "statue24",
    type: "statue",
  },
  {
    id: 216,
    src: "/images/models/statue/statue25.png",
    title: "statue25",
    type: "statue",
  },
  {
    id: 217,
    src: "/images/models/statue/statue26.png",
    title: "statue26",
    type: "statue",
  },
  {
    id: 218,
    src: "/images/models/statue/statue27.png",
    title: "statue27",
    type: "statue",
  },
  {
    id: 164,
    src: "/images/models/statue/statue28.png",
    title: "statue28",
    type: "statue",
  },
  {
    id: 165,
    src: "/images/models/statue/statue29.png",
    title: "statue29",
    type: "statue",
  },
  {
    id: 219,
    src: "/images/models/vases/vase-01.png",
    title: "vase-01",
    type: "vases",
  },
  {
    id: 220,
    src: "/images/models/vases/vase-02.png",
    title: "vase-02",
    type: "vases",
  },
  {
    id: 221,
    src: "/images/models/vases/vase-03.png",
    title: "vase-03",
    type: "vases",
  },
  {
    id: 222,
    src: "/images/models/vases/vase-04.png",
    title: "vase-04",
    type: "vases",
  },
  {
    id: 223,
    src: "/images/models/vases/vase-05.png",
    title: "vase-05",
    type: "vases",
  },
  {
    id: 224,
    src: "/images/models/vases/vase-06.png",
    title: "vase-06",
    type: "vases",
  },
  {
    id: 225,
    src: "/images/models/vases/vase-07.png",
    title: "vase-07",
    type: "vases",
  },
  {
    id: 226,
    src: "/images/models/vases/vase-08.png",
    title: "vase-08",
    type: "vases",
  },
  {
    id: 227,
    src: "/images/models/vases/vase-09.png",
    title: "vase-09.",
    type: "vases",
  },
  {
    id: 228,
    src: "/images/models/vases/vase-10.png",
    title: "vase-10",
    type: "vases",
  },
  {
    id: 166,
    src: "/images/models/vases/vase-brass.png",
    title: "vase-brass",
    type: "vases",
  },
  {
    id: 167,
    src: "/images/models/vases/vase-bronze.png",
    title: "vase-bronze",
    type: "vases",
  },
  {
    id: 168,
    src: "/images/models/vases/vase-metal_4inch.png",
    title: "vase-metal_4inch",
    type: "vases",
  },
  {
    id: 169,
    src: "/images/models/vases/vase-metal_5inch.png",
    title: "vase-metal_5inch",
    type: "vases",
  },
  {
    id: 170,
    src: "/images/models/vases/vase-metal_6inch.png",
    title: "vase-metal_6inch",
    type: "vases",
  },
  {
    id: 229,
    src: "/images/models/ceramics/Heart_6x6.png",
    title: "Heart_6x6",
    type: "ceramics",
  },
  {
    id: 230,
    src: "/images/models/ceramics/Heart_8x8.png",
    title: "Heart_8x8",
    type: "ceramics",
  },
  {
    id: 231,
    src: "/images/models/ceramics/Oval_1.75x2.25.png",
    title: "Oval_1.75x2.25",
    type: "ceramics",
  },
  {
    id: 232,
    src: "/images/models/ceramics/Oval_2.25x2.75.png",
    title: "Oval_2.25x2.75",
    type: "ceramics",
  },
  {
    id: 233,
    src: "/images/models/ceramics/Oval_2.625x3.375.png",
    title: "Oval_2.625x3.375",
    type: "ceramics",
  },
  {
    id: 234,
    src: "/images/models/ceramics/Oval_3.25x4.25.png",
    title: "Oval_3.25x4.25",
    type: "ceramics",
  },
  {
    id: 235,
    src: "/images/models/ceramics/Oval_3.75x5.png",
    title: "Oval_3.75x5",
    type: "ceramics",
  },
  {
    id: 236,
    src: "/images/models/ceramics/Oval_4.25x6.png",
    title: "Oval_4.25x6",
    type: "ceramics",
  },
  {
    id: 237,
    src: "/images/models/ceramics/Oval_5x7.png",
    title: "Oval_5x7",
    type: "ceramics",
  },
  {
    id: 238,
    src: "/images/models/ceramics/Oval_8x10.png",
    title: "Oval_8x10",
    type: "ceramics",
  },
  {
    id: 239,
    src: "/images/models/ceramics/Rectangle_10x22.png",
    title: "Rectangle_10x22",
    type: "ceramics",
  },
  {
    id: 240,
    src: "/images/models/ceramics/Rectangle_4x6.png",
    title: "Rectangle_4x6",
    type: "ceramics",
  },
  {
    id: 241,
    src: "/images/models/ceramics/Rectangle_8x10.png",
    title: "Rectangle_8x10",
    type: "ceramics",
  },
  {
    id: 242,
    src: "/images/models/ceramics/Round_3.5.png",
    title: "Round_3.5",
    type: "ceramics",
  },
  {
    id: 243,
    src: "/images/models/ceramics/Round_5.png",
    title: "Round_5",
    type: "ceramics",
  },
  {
    id: 244,
    src: "/images/models/ceramics/Round_6.png",
    title: "Round_6",
    type: "ceramics",
  },
  {
    id: 245,
    src: "/images/models/ceramics/Round_8.png",
    title: "Round_8",
    type: "ceramics",
  },
  {
    id: 246,
    src: "/images/models/ceramics/Square_4x4.png",
    title: "Square_4x4",
    type: "ceramics",
  },
  {
    id: 247,
    src: "/images/models/ceramics/Square_6x6.png",
    title: "Square_6x6",
    type: "ceramics",
  },

  {
    id: 248,
    src: "/images/models/bronze/bronze_16x24.png",
    title: "bronze_16x24",
    type: "bronze",
  },
  {
    id: 249,
    src: "/images/models/bronze/bronze_24x10.png",
    title: "bronze_24x10",
    type: "bronze",
  },
  {
    id: 250,
    src: "/images/models/bronze/bronze_24x12.png",
    title: "bronze_24x12",
    type: "bronze",
  },
  {
    id: 251,
    src: "/images/models/bronze/bronze_24x14.png",
    title: "bronze_24x14",
    type: "bronze",
  },
  {
    id: 252,
    src: "/images/models/bronze/bronze_24x30.png",
    title: "bronze_24x30",
    type: "bronze",
  },
  {
    id: 253,
    src: "/images/models/bronze/bronze_36x13.png",
    title: "bronze_36x13",
    type: "bronze",
  },
  {
    id: 254,
    src: "/images/models/bronze/bronze_44x14 .png",
    title: "bronze_44x14",
    type: "bronze",
  },
];

export default images;
